# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remark', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(max_length=150)),
                ('course_name', models.ManyToManyField(related_name='student_course', to='courses.Courses')),
            ],
        ),
    ]
