# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendnotification',
            name='course',
        ),
        migrations.AlterField(
            model_name='students',
            name='student_Id',
            field=models.CharField(default='STU20178ZOI402', max_length=200),
        ),
    ]
