# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='course_name',
            field=models.ManyToManyField(to='courses.Courses'),
        ),
    ]
