# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_name', to='courses.Courses')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentfee',
            name='student',
        ),
        migrations.AddField(
            model_name='students',
            name='height_field',
            field=models.IntegerField(default=600, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='picture',
            field=models.ImageField(blank=True, default='/students/img/default.png', height_field='height_field', null=True, upload_to='', verbose_name='profile picture', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='students',
            name='width_field',
            field=models.IntegerField(default=600, null=True),
        ),
        migrations.DeleteModel(
            name='StudentFee',
        ),
        migrations.AddField(
            model_name='studentpaymentdetail',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_name', to='students.Students'),
        ),
    ]
