# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20170819_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpaymentdetail',
            name='student',
        ),
        migrations.AlterField(
            model_name='students',
            name='student_Id',
            field=models.CharField(default='STU2017822SLST', max_length=200),
        ),
    ]
