# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20170808_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpaymentdetail',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_name', to='students.Students'),
        ),
    ]
