# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-04 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course_name',
            field=models.ManyToManyField(related_name='student_course', to='courses.Courses'),
        ),
    ]
