# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_sendnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpaymentdetail',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
