# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20170819_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_Id',
            field=models.CharField(default='STU20178A9XRYS', max_length=200),
        ),
    ]
