# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20170828_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_Id',
            field=models.CharField(default='STU20178B651YP', max_length=200),
        ),
    ]
