# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20170819_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpaymentdetail',
            name='student',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_Id',
            field=models.CharField(default='STU20178L54ZH9', max_length=200),
        ),
    ]
