# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20170828_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_Id',
            field=models.CharField(default='STU20178IVZHWR', max_length=200),
        ),
    ]
