# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20170830_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_Id',
            field=models.CharField(default='STU20178MKWODJ', max_length=200),
        ),
    ]
