# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 23:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone Number should be valid of 10 digits only', regex='^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$')]),
        ),
    ]
