# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPro', '0002_auto_20170828_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=256),
        ),
    ]
