# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quarterly_fee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('yearly_fee', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
