# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 22:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monthly Fee')),
                ('quarterly_fee', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Quarterly Fee')),
                ('yearly_fee', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Yearly Fee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
